### PR TITLE
Prototype

### PR DESCRIPTION
**Pull request by kwu3**
Fixes # .

Changes Proposed in this pull request:
* Fix Everything
* Add Cookies
* Profit!

### CODE REVIEW

**Comment by kwu3** [comment]
Ok, since you like the dialog, I can move on. delete stuffs is easy :). Here is what i am going to do. Add a NPC to the git (move the current one there). If I have time, I will add the gate there. If more, I may add another trigger there to change the dialog of the NPC.  

However, what i will not touch is the STOP player when trigger (till i learn the script code) or i will move the current player there for now, so we have a NPC to play and we can always replace it when we figure our the first person view character you are using. Please let me know if this works for you.

**Comment by chbachman** [comment]
That's good. Add it to the Main scene/testing world and you'll be done. Nicholas will handle the world/gate.

**Comment by chbachman** [comment]
Can you combine the Assets and Assets for Prototype Folder? There shouldn't be two disparate folders containing assets. As well, can you please delete any unused scripts?

If you can't I'll go through your branch and clean it up.

**Comment by chbachman** [comment]
I'm going to be using this a critique of the code styles I see in this project.

* Booleans exist in C#. Use them. Don't use ints and check 0 or 1. This isn't C.
* Start all class names with Capital Letters, using CamelCase. e.g. `NextScene` vs `nextscene`
* Remove all unrelated Script Files, such as traget.cs or nextscene.cs
* Don't create a separate folder, combine folders. For example, you have a prefab folder inside of the Assets for prototype folder. Don't do this. Instead create the prefabs inside of the Prefab folder.
* Remove commented out lines before creating a PR. A PR should contain only finalized code, not code that has commented out lines or debug statements.
* Remove unused components, such as RestartOnClick

**Pull request merged**
